removing error code drop down
NHSDigital/nhs-login-help-centre pull request #35
Opened 2020-12-09 16:41 UTC by infinitydeep

removing drop down for error codes, this MR means it should be automatically filled where possible instead.

2020-12-09 16:54 UTC, Olie440 requested changes

2020-12-09 16:54 UTC, Olie440 commented on src/js/contact-page.js
> +  function getLinks() {
I would rename this to be something like `getErrorCode`

2020-12-09 16:54 UTC, Olie440 commented on src/js/contact-page.js
> +    const { errorCode, linkText } = getLinks();
Maybe these could be renamed `code` and `description` you can find the code that creates the object here: https://github.com/NHSDigital/nhs-login-help-centre/blob/develop/lib/article.js#L45

2020-12-09 16:54 UTC, Olie440 commented on src/js/contact-page.js
> +  const errorCode = Utils.getParam('error') || 'Unknown';
I don't think we need this since we have an or on the find

2020-12-09 16:56 UTC, Olie440 commented on src/js/contact-page.js
> +  const errorCode = Utils.getParam('error') || 'Unknown';
I think as well it could probs be moved into the function as well

2020-12-11 15:00 UTC, infinitydeep commented on src/js/contact-page.js
> +  function getLinks() {
done

2020-12-11 15:00 UTC, infinitydeep commented on src/js/contact-page.js
> +    const { errorCode, linkText } = getLinks();
done

2020-12-11 15:00 UTC, infinitydeep commented on src/js/contact-page.js
> +  const errorCode = Utils.getParam('error') || 'Unknown';
done

2020-12-11 15:03 UTC, Olie440 requested changes

2020-12-11 15:03 UTC, Olie440 commented on src/js/contact-page.js
> +    if (errorCodeRegex.test(errorCode)) {
This looks to be missing the description, I also think the logic is slightly off.
The logic should be: 
- test if its a valid error code
- if it isn't return `{ code: 'UNKNOWN', description: 'UNKNOWN' }`
- if it is search for it
- if theres a match return the match
- if theres not a match then return the code and description from the getParams (defaulting to unknown if missing)

2020-12-11 15:57 UTC, Olie440 requested changes

2020-12-11 15:57 UTC, Olie440 commented on src/js/contact-page.js
> +          { code: errorCode, description: errorDesc } || { code: 'UNKNOWN', description: 'UNKNOWN' }
This would never return the second one since the you are declairing the object here. 
Looking at how the code is set up you could do this:
```js
const errorDesc = Utils.getParam('desc') || 'UNKNOWN';
// ....
return  { code: errorCode, description: errorDesc };

```

2020-12-11 15:57 UTC, Olie440 commented on src/js/contact-page.js
> +    } else {
Since this is an edge case it should be an early return like this:
```js
if (!errorCodeRegex.test(errorCode)) {
   return { code: 'UNKNOWN', description: 'UNKNOWN' };
}
```

2020-12-11 15:57 UTC, Olie440 commented on src/js/contact-page.js
> +      if (errorMatch) {
This could be an or statment like before:
```js
return errorMatch || { code: errorCode, description: errorDesc };
```

2020-12-11 16:38 UTC, Olie440 commented on src/js/contact-page.js
> +    if (errorMatch) {
No need for these if you are using `||`. Think about it:
- if errorMatch is truthy it will go in here and then always return errorMatch since it is truthy
- if errorMatch is falsy it will go into the bottom one and return that object, meaning that the || is unneeded

2020-12-11 17:01 UTC, Olie440 approved these changes

2020-12-14 12:20 UTC, Tomo-Dachi approved these changes

2020-12-14 12:26 UTC, lps88 commented
approved by Alex Murphy (tomo-dachi)

2020-12-14 12:26 UTC, merged